# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
######3333duheduyged
name: CI/CD Workflow

on:
  push:
    branches:
      - dev
      - main

jobs:
  # Step 1: Build and Test on dev Branch
  build-and-test-on-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose


      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and test using Docker Compose
      - name: Build and test using Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose exec backend npm test
          docker-compose exec frontend npm test
          docker-compose down

  # Step 2: Automatically Merge dev into main
  merge-dev-to-main:
    needs: build-and-test-on-dev
    if: github.ref == 'refs/heads/dev' && success()
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Merge dev into main
      - name: Merge dev into main
        run: |
          git checkout main
          git merge --no-ff dev
          git push origin main

  # Step 3: Build, Test, and Deploy on main Branch
  build-test-and-deploy-on-main:
    needs: merge-dev-to-main
    if: github.ref == 'refs/heads/main' && success()
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and test using Docker Compose
      - name: Build and test using Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose exec backend npm test
          docker-compose exec frontend npm test

      # Run E2E tests
      - name: Run E2E Tests
        run: |
          docker-compose exec frontend npm run e2e-tests

      # Build and push Docker images
      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

      # Shut down Docker Compose
      - name: Shut down Docker Compose
        run: docker-compose down
